baseURL = "https://issei0804-ie.github.io/Issei0804-ie"
title = "home"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
theme = "hugo-theme-basic"
publishDir = "docs"

[[params.menu]]
  name = "work"
  url = "work/"

[[params.menu]]
  name = "about_me"
  url = "about"

[[params.menu]]
  name = "etc"
  url = "etc/"
