 name: generate-html-with-hugo
 
 on:
   push:
     branches:
       - "main"
 
 env:
   PUBLISH_DIR: "./docs"
   PUBLISH_BRANCH: "gh-pages"
 
 jobs:
   generate-html:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Set up Go 1.9
         uses: actions/setup-go@v2
         with:
           go-version: 1.9
       - run: CGO_ENABLED=1 go install --tags extended github.com/gohugoio/hugo@latest
       - run: hugo
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ${{ env.PUBLISH_DIR }}
           publish_branch: ${{ env.PUBLISH_BRANCH }}
